# Generated by Django 5.1.7 on 2025-03-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
