# Generated by Django 4.1.13 on 2025-03-15 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('Open Profile', 'Open Profile'), ('Private Profile', 'Private Profile')], default='Open Profile', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
